[tools]
# give some default global versions
ruby = "latest"
node = "22.14.0"

[settings]
# should we just add all of the supported ones?
# https://mise.jdx.dev/configuration.html#idiomatic-version-files
idiomatic_version_file_enable_tools = ["ruby", "node"]

# so we don't have to run `mise trust` as part of bin/setup
trusted_config_paths = [
    '~/workspace',
]

# TODO: Move stuff out of config_files/init.sh
# https://github.com/Gusto/config_files/blob/88019060433bae4b075b098fc4770f191f2ce20d/init.sh#L56-L57
# I'm not sure exactly how the tools.node.corepack = true would work
not_found_auto_install = false
