#!/bin/env zsh

CREDS_FILE=~/.aws/credentials
#CREDS_FILE=./creds  # testing script
SED=$(command -v sed)

if ! grep -qF "172852125925" "$CREDS_FILE"; then
   echo "gimme_aws_creds hasn't been run recently.  Please run first before attempting to fix"

else
  echo "continuing..."

  if command -v gsed &> /dev/null; then
      echo "gsed found, using..."
      SED=$(command -v gsed)
  fi

  # first remove old sections if they exist
  $SED -z 's#\[aws-wme-entertainment:aws-wme-entertainment-devops.*\[#[#g' -i "$CREDS_FILE"
  $SED -i 's#172852125925#aws-wme-entertainment#g' "$CREDS_FILE"
fi
